# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('active', models.IntegerField(default=0)),
                ('modify', models.IntegerField(default=0)),
                ('notified', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_name', models.CharField(max_length=50)),
                ('shoe_description', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('shoe_price', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyshoes.Shoe'),
        ),
    ]
